layout_spectrum: 0.7939068
color:
  saturation: 0.6753204
  lightness: 0.434357
  brandStrength: 0.3044911
  brandColors:
    - '#FFFFFF'
    - '#151A11'
    - '#688354'
    - '#3A4E32'
    - '#93B672'
  rhythmicContrast: 0.03353885
typography_spectrum: 0.9032258
name: Yamasil
